import turtle
turtle.pensize(3)
turtle.color("orangered")
turtle.right(-134)
turtle.fillcolor("red")
turtle.shape('blank')
turtle.speed(1)
turtle.begin_fill ()
turtle.circle (-600,20)
turtle.circle(-60,180)
turtle.right(-135)
turtle.circle (-60,180)
turtle.circle (-598,20)
turtle.end_fill ()
