myfile = open("C:\\Users\\24521\\Desktop\\use.txt", "w")
a = input()
myfile.write(a)
myfile.close()
# cont = myfile.read()
# myfile.write("write in flie")
# print(cont)
myfile = open("C:\\Users\\24521\\Desktop\\use.txt", "r")
print(myfile.read())
myfile.close()